Student_Name=input("Enter Student Name :")
Percentage=int(input("Enter Percentage:"))
Family_Annual_Income=int(input("Enter family annual income:"))

if(Percentage>= 90 and Family_Annual_Income<300000):
    print("="*34)
    print("SCHOLARSHIP RESULT".center(34))
    print("="*34)
    print(f"{"Studen Name":<15}:{Student_Name}")
    print(f"{"Percentage":<15}:{Percentage}")
    print(f"{"Income":<15}:{Family_Annual_Income}")
    print(f"{"Scholarship ":<15}:{"100%"}")
    print(f"{"Status":<15}:{"Eligible"}")
    print("-"*34)
elif((Percentage>= 80 ) and Family_Annual_Income<500000):
    print("="*34)
    print("SCHOLARSHIP RESULT".center(34))
    print("="*34)
    print(f"{"Studen Name":<15}:{Student_Name}")
    print(f"{"Percentage":<15}:{Percentage}")
    print(f"{"Income":<15}:{Family_Annual_Income}")
    print(f"{"Scholarship ":<15}:{"50%"}")
    print(f"{"Status":<15}:{"Eligible"}")
    print("-"*34)
elif(Percentage>= 70  ):
    print("="*34)
    print("SCHOLARSHIP RESULT".center(34))
    print("="*34)
    print(f"{"Studen Name":<15}:{Student_Name}")
    print(f"{"Percentage":<15}:{Percentage}")
    print(f"{"Income":<15}:{Family_Annual_Income}")
    print(f"{"Scholarship ":<15}:{"25%"}")
    print(f"{"Status":<15}:{"Eligible"}")
    print("-"*34)
else:
    print("="*34)
    print("SCHOLARSHIP RESULT".center(34))
    print("="*34)
    print(f"{"Studen Name":<15}:{Student_Name}")
    print(f"{"Percentage":<15}:{Percentage}")
    print(f"{"Income":<15}:{Family_Annual_Income}")
    print(f"{"Scholarship ":<15}:{"Not Eligible"}")
    print(f"{"Status":<15}:{" Not Eligible"}")
    print("-"*34)
    