Student_Name=input("Enter student name:")
Python_Mark=int(input("Enter Python Mark:"))
Mathematics_Mark=int(input("Enter Mathematics Mark:"))
English_Mark=int(input("Enter English Mark:"))
Science_Mark=int(input("Enter Science Mark:"))
Computer_Mark=int(input("Enter Computer Mark:"))

print("="*34)
print("REPORT CARD".center(34))
print("="*34)
print(f"{"Student Name":<15}:{Student_Name}")
print(f"{"Python":<15}:{Python_Mark}")
print(f"{"Mathematics":<15}:{Mathematics_Mark}")
print(f"{"English":<15}:{English_Mark}")
print(f"{"Science":<15}:{Science_Mark}")
print(f"{"Computer":<15}:{Computer_Mark}")
print("-"*34)
total=Python_Mark+Mathematics_Mark+English_Mark+Science_Mark+Computer_Mark
print(f"{"total":<15}:{total}")
print(f"{"Average":<15}:{total/5}")
print(f"{"persentage":<15}:{(total/5)}")
print("="*34)
